---
title: "Midterm Errors"
author: "Olivia Beck"
date: '2022-10-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Used to generate Midterm question 3 


```{r}
library(tidyverse)
library(dcData)


str(mtcars)
head(mtcars)
```

## Part A 

#### Incorrect Code


```{r}
Humans <-
  StarWars %>%
  select(species == "Human")
```
#### Correct Code 

```{r}
Humans <-
  StarWars %>%
  filter(species == "Human")
  
```


## Part B

#### Incorrect Code 

```{r}
WorldPops <- 
  StarWars %>%
  group_by(homeworld) 
  summarise(population = sum())

```



#### Correct Code 

```{r}
WorldPops <- 
  StarWars %>%
  group_by(homeworld) %>%
  summarise(population = n())

```



## Part C

#### Incorrect Code 

```{r}
SpeciesHeights <-
  StarWars %>%
  group_by(species) %>%
  (average = mean(height, na.rm = TRUE))
```



#### Correct Code 

```{r}
SpeciesHeights <-
  StarWars %>%
  group_by(species) %>%
  summarise(average = mean(height, na.rm = TRUE))

```



## Part D

#### Incorrect Code

```{r}
C-3PO <- 
  StarWars %>%
  filter(name == "C-3PO")
```

#### Correct Code

```{r}
C3PO <- 
  StarWars %>%
  filter(name == "C-3PO")
```
